.\" Version: 2020-11-26 18_00
.\"
.TH sapping 8 "26 11 2020" "" "sapstartsrv-resource-agents"
.\"
.SH NAME
sapping \- hiding sapservices file from sapinit service at system boot.
.PP
.\"
.SH SYNOPSYS
\fBsapping\fP
.PP
.\"
.SH DESCRIPTION
\fBsapping\fP is a systemd service for  hiding sapservices file from sapinit service at system boot.
.\" TODO
.PP
.\"
.SH EXIT STATUS
0 Successful program execution.
.br
>0 Usage, syntax or execution errors.
.PP
.\"
.SH FILES
.TP
/usr/sbin/sapping
systemd service executable 
.TP
/usr/lib/systemd/system/sapping.service
systemd service definiton
.TP
/usr/sap/sapservices
SAP profiles definition file, used by sapstartsrv et al.
.PP
.\"
.SH BUGS
Please report feedback and suggestions to feedback@suse.com.
.PP
.\"
.SH SEE ALSO
\fBocf_heartbeat_SAPStartSrv\fP(7) , \fBsappong\fP(8),  \fBsystemctl\fP(1)
.PP
.\"
.SH AUTHORS
X.Arbulu, F.Herschel, L.Pinne
.PP
.\"
.SH COPYRIGHT
.br
(c) 2020 SUSE LLC
.br
The resource agent SAPStartSrv comes with ABSOLUTELY NO WARRANTY.
.br
For details see the GNU General Public License at
http://www.gnu.org/licenses/gpl.html
.\"
