.\" Version: 2020-11-26 18_00
.\"
.TH sapping 8 "26 11 2020" "" "SAPStartSrv"
.\"
.SH NAME
sapping \- hiding sapservices file from sapinit.service at system boot.
.PP
.\"
.SH SYNOPSYS \fBsapping\fP
.PP
.\"
.SH DESCRIPTION
\fBsapping\fP is a systemd service for  hiding sapservices file from sapinit.service at system boot.
.PP
.\"
.SH RETURN CODES
The return codes are defined by the OCF cluster framework. Please refer to the O
CF definition on the website mentioned below. 
.PP
.\"

