.\ Version: 0.1.0
.\"
.TH SAPStartSrv_maintenance_examples 7 "03 Feb 2021" "" "SAPStartSrv"
.\"
.SH NAME
SAPStartSrv_maintenance_examples \- maintenance examples for SAPStartSrv
.PP
.\"
.SH DESCRIPTION
.\"
Maintenance examples for SAPStartSrv and SUSE HA for SAP Enqueue Standalone
clusters.
Please see ocf_suse_SAPStartSrv(7), SAPStartSrv_basic_cluster(7) and sap_suse_cluster_connector(8) for more examples and read the REQUIREMENTS section there.
.PP
.\"
.SH EXAMPLES
.PP

.PP
.\"
.SH BUGS
Please report feedback and suggestions to feedback@suse.com.
.PP
.\"
.SH SEE ALSO
\fBocf_suse_SAPStartSrv\fP(7) ,  \fBSAPStartSrv_basic_cluster\fP(7) ,
\fBsap_suse_cluster_connector\fP(8) ,
\fBcrm\fP(8) , \fBcrm_simulate\fP(8) , \fBcibadmin\fP(8) ,
\fBsbd\fP(8) , \fBcorosync-cfgtool\fP(8) ,
\fBsystemctl\fP(8) ,
\fBcs_clusterstate\fP(8) , \fBcs_show_ensa_status\fP(8) ,
.PP
.\"
.SH AUTHORS
F.Herschel, L.Pinne
.PP
.\"
.SH COPYRIGHT
.br
(c) 2020-2021 SUSE LLC
.br
SAPStartSrv comes with ABSOLUTELY NO WARRANTY.
.br
For details see the GNU General Public License at
http://www.gnu.org/licenses/gpl.html
.\"
