.\" Version: 0.1.0
.\"
.TH SAPStartSrv_basic_cluster 7 "11 12 2020" "" "SAPStartSrv"
.\"
.SH NAME
SAPStartSrv_basic_cluster \- basic settings to make SAPStartSrv work
.\" TODO description
.PP
.\"
.SH DESCRIPTION
.PP
.\"
.SH EXAMPLES
.\" TODO OS network tcp_retries2=8 (8..10)
.\" TODO scenario specific CIB basic settings
.\" TODO priority fencing: use case, setup
.\" TODO pingd: use case, setup
.PP
.\"
.SH FILES
.\" TODO
.PP
.\"
.SH BUGS
Please report feedback and suggestions to feedback@suse.com.
.PP
.\"
.SH SEE ALSO
\fBocf_suse_SAPStartSrv\fP(7) , \fBsap_suse_cluster_connector\fP(8) ,
\fBocf_pacemaker_ping\fP(7) , \fBocf_heartbeat_ethmonitor\fP(7) ,
\fBsbd\fP(8) , \fBstonith_sbd\fP(8) , \fBcorosync.conf\fP(5) ,
\fBvotequorum\fP(5)
.PP
.\"
.SH AUTHORS
F.Herschel, L.Pinne
.PP
.\"
.SH COPYRIGHT
.br
(c) 2020 SUSE LLC
.br
SAPStartSrv comes with ABSOLUTELY NO WARRANTY.
.br
For details see the GNU General Public License at
http://www.gnu.org/licenses/gpl.html
.\"

	
	
	
	

