sudo: required
services:
  - docker

language: python

stages:
  - test
  - delivery
  - submit

jobs:
  include:
    - stage: test
      python: 2.7
      install:
          - pip install pytest pytest-cov mock
      script:
          - py.test -vv --cov=SAPStartSrv --cov-report term tests

    - stage: test
      python: 3.6
      before_script:
          - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          - chmod +x ./cc-test-reporter
          - ./cc-test-reporter before-build
      install:
          - pip install pytest pytest-cov mock
      script:
          - py.test -vv --cov=SAPStartSrv --cov-report term --cov-report xml tests
      after_script:
          - mv tests/coverage.xml .
          - ./cc-test-reporter after-build -t coverage.py --exit-code $TRAVIS_TEST_RESULT tests/coverage.xml

    - stage: delivery
      if: type != pull_request
      env:
        - FOLDER=/package
        - PACKAGE_NAME=sapstartsrv-resource-agent

      before_install:
        - docker pull shap/continuous_deliver:latest

      script:
        - |
          docker run -t -v "$(pwd):/package" -w /package \
          -e OBS_USER -e OBS_PASS -e FOLDER -e OBS_PROJECT -e PACKAGE_NAME \
          shap/continuous_deliver \
          /scripts/upload.sh

    - stage: submit
      if: type != pull_request AND branch = master
      env:
        - PACKAGE_NAME=sapstartsrv-resource-agent

      before_install:
        - docker pull shap/continuous_deliver:latest

      script:
        - |
          docker run -t -v "$(pwd):/package" -w /package \
          -e OBS_USER -e OBS_PASS -e OBS_PROJECT -e PACKAGE_NAME -e TARGET_PROJECT shap/continuous_deliver \
          /scripts/submit.sh
