#!/bin/sh
#
# sappong
#
sapservices="/usr/sap/sapservices"
#
# document current sapservices status and content
#
ls -la "$sapservices"
cat "$sapservices"
#
# restore sapservices back if size = 0
#
if [ -n "$(find $sapservices -size 0)" ]; then
    mv "$sapservices".moved "$sapservices"
else
    echo "skip restoring sapservices";
fi
ls -la "$sapservices"
