#!/bin/sh
#
# sapping
#
# (c) 2020 SUSE LLC
# Author: F.Herschel
# GNU General Public License v2. No warranty.
# http://www.gnu.org/licenses/gpl.html
#
# Version: 2020-11-26
#
sapservices="/usr/sap/sapservices"
#
# document current sapservices status and content
#
ls -la "$sapservices"
cat "$sapservices"
#
# move sapservices if size > 0
#
if [ -n "$(find $sapservices -size 0)" ]; then
    echo "skip moving sapservices";
else
    touch "$sapservices".empty
    mv "$sapservices" "$sapservices".moved
    mv "$sapservices".empty "$sapservices"
fi
ls -la "$sapservices"
#
