#!/bin/sh
#
# sapservices-move
#
# (c) 2020 SUSE LLC
# Author: F.Herschel, L.Pinne
# GNU General Public License v2. No warranty.
# http://www.gnu.org/licenses/gpl.html
#
# TODO error handling
#

scriptversion="2020-11-27 08:44"
scriptname="$(basename $0)"
sapservices="/usr/sap/sapservices"


function do_help() {
	echo "usage: $scriptname [OPTION]"
	echo
	echo " --help		show help"
	echo " --version	show version"
	echo " --hide		move away $sapservices"
	echo " --unhide     restore $sapservices"
	echo
}


function do_cat() {
	#
	# document current sapservices status and content
	#
	ls -la "$sapservices"
	cat "$sapservices"
}


function do_ping() {
	do_cat
	#
	# move sapservices if size > 0
	#
	if [ -n "$(find $sapservices -size 0)" ]; then
		echo "skip moving sapservices";
	else
		touch "$sapservices".empty
 		mv "$sapservices" "$sapservices".moved
		mv "$sapservices".empty "$sapservices"
	fi
	ls -la "$sapservices"
}


function do_pong() {
	do_cat
	#
	# restore sapservices back if size = 0
	#
	if [ -n "$(find $sapservices -size 0)" ]; then
		mv "$sapservices".moved "$sapservices"
	else
		echo "skip restoring sapservices";
	fi
	ls -la "$sapservices"
}


# main()
case $1 in
	-v|--version)
		echo "version: $scriptversion"
	;;
	-m|--hide|--move)
		do_ping
	;;
	-u|--unhide)
		do_pong
	;;
	*)
		do_help
	;;
esac
#
