#!/bin/bash
#
# SAPHanaSR-alert-failing
# Author:       Lars Pinne, Fabian Herschel, 2026
# Support:      linux@sap.com
# License:      GNU General Public License (GPL)
# Copyright:    (c) 2026 SUSE LLC
# Version:	    2026-08-13-14:20
#
# https://oneuptime.com/blog/post/2026-03-04-configure-pacemaker-alerts-and-notifications-on-rhel/view
# https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/7/html/high_availability_add-on_reference/ch-alertscripts-haar
#
# crm configure alert failure-1 "/usr/bin/SAPHanaSR-alert-failure" select failure attributes <resource>
# TODO: attribute = path to custom script?
# TODO: attribute = resource to react on?
# TODO: timeout 30s default okay?
#

logger_tag="SAPHanaSR-alert-failing"
logger="/usr/bin/logger"

crm_alert_recipient="${CRM_alert_recipient:-/dev/null}"
crm_alert_kind="${CRM_alert_kind:-manual call}"         # node, fencing, resource, attribute
crm_alert_node="${CRM_alert_node:-$HOSTNAME}"
crm_alert_desc="${CRM_alert_desc:-no description}"
crm_alert_status="${CRM_alert_status:-no status}"
# CRM_alert_rc
# CRM_alert_target_rc
crm_alert_rsc="${CRM_alert_rsc:-no resource}"

$logger -t "$logger_tag" "AH: begin event '$crm_alert_kind'"

function process_failure()
{
    /bin/true
}

case "$crm_alert_kind" in
    node|nodes)
        msg="Node '${crm_alert_node}' is now '${crm_alert_desc}'"
        $logger -t "$logger_tag" "INFO: $msg"
        ;;
    fencing)
        msg="Fencing '${crm_alert_node}' is now '${crm_alert_desc}'"
        $logger -t "$logger_tag" "INFO: $msg"
        ;;
    resource)
        msg="Resource '${crm_alert_rsc}' is now '${crm_alert_status}'"
        $logger -t "$logger_tag" "INFO: $msg"
        process_failure
        ;;
    *)
	msg="Unhandled '$crm_alert_kind' alert (${crm_alert_desc})"
        $logger -t "$logger_tag" "INFO: $msg"
        ;;
esac
$logger -t "$logger_tag" "AH: end event '$crm_alert_kind'"
#
