#!/usr/bin/bash
#
# SAPInstance-Helper
# Author:       F.Herschel, L.Pinne, 2026
# Support:      linux@sap.com
# License:      GNU General Public License (GPL)
# Copyright:    (c) 2026 SUSE LLC
# Version:      2026-08-15-00:00
#
# params: cmd InstanceName
#

logger_tag="SAPInstance-helper"
logger="/usr/bin/logger"
cmd="$1"
InstanceName="$2"

function process_stack()
{
    sPID="$(pgrep -f "sapstartsrv.*${InstanceName}")"
    echo "pgrep -f sapstartsrv.*${InstanceName}"
    $logger -i -t "$logger_tag" "PID of sapstartsrv is $sPID"
}
function process_log()
{
    # TODO permissions on /var/log/*.log ?
    sudo /usr/sbin/psauxlog /var/log/psaux.log
    sudo /usr/sbin/meminfolog /var/log/meminfo.log
    # TODO add when new ClusterTools2 ships
    #/usr/sbin/vmstatlog /var/log/vmstat.log
    # wildcards do not work for lsof
    sudo /usr/sbin/lsoflog /var/log/lsof.log "+D/usr/sap/${SID}/" 22
}

function process_log_stack()
{
    process_stack 
    process_log
}

$logger -i -t "$logger_tag" "Called with $* (as $(id))"
case "$cmd" in
    log+stack ) process_log_stack
                ;;
esac
exit 0
# 
